### ISSUE TITLE
resolve database conflicts

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery-dashboard#119]
if the conflict is between the device and the database, and the database change is prior to the device, then use the mobile device. otherwise, use the database

**Comment by jofomah** [comment]
Currently, the mobile app sync works as follows:
- replicate remote to local db.
- replicate local to remote

This is enough for current work-flow where all schedule changes are mostly one time thing during round import.

With the migration from Google sheet to dashboard, there is a tendency for changes to occur frequently from the Dashboard Admin panel.

We need a solution that works as follow or whatever makes more sense:
- sync remote and local as it is done currently.
- For documents with conflict and date before and including current date, local copy wins and will be used to overwrite remote copy (because i feel whatever data is on the mobile app should get to the server)
- For documents with conflicts and date after current date, remote copy wins i.e for upcoming schedules, the remote copy or changes should be used to overwrite the local copy if there is conflict.

Please let me know what you think or what alternatives might work better!

**Comment by tlvince** [comment]
This is non-trivial. Do we have any metrics/past data on instances where conflicts have happened?

**Comment by tlvince** [comment]
Splitting up `dailyDelivery` docs will go along way towards reducing conflicts to start with. Ref https://github.com/eHealthAfrica/direct-delivery/pull/253

**Comment by tlvince** [comment]
Reverse sorting by `_rev` will give you an idea of which documents are modified often:

``` js
function(doc) {
  emit(doc._rev)
}
```

Cherry-picking a few instances shows high rev counts (> 30) on `dailyDelivery` docs.

**Comment by tlvince** [comment]
I sense this is a case of "prevention vs cure". If we remodel the docs that are causing high rev counts, we'd reduce the likelihood of conflicts.

For example, the parts of a `dailyDelivery` doc that are sensitive to change include:
- `facilityRounds` (fixed by flattening in https://github.com/eHealthAfrica/direct-delivery/pull/253, should yield the greatest gain)
- `packingList` (as set by a planner/admin)
- `packedProduct` (updated incrementally by a driver)
- `driverID`
- `date`
- `facilityKPI` (updated at the end of the round?)

After https://github.com/eHealthAfrica/direct-delivery/pull/253, `packingList` and `packedProduct` are the only remaining lists. We could start by splitting those into [one-to-n relations](https://github.com/eHealthAfrica/couchdb-best-practices#one-to-n-relations)?

**Comment by tlvince** [comment]
@jofomah thoughts on this?

**Comment by jofomah** [comment]
@tlvince sorry just saw this, always ping me on slack if it is urgent because i filter github notifications.

you want us to split packed product into its own document??

This will lead to re-writing most of the dashboard parts and not just the mobile app end.  i think we can keep it simple now and let the refactoring be part of the next phase which is turning VDD into SaaS, we will consider all these in the Architectural design.

**Comment by tlvince** [comment]
Yes, these refactors should be consider for the long run. https://github.com/eHealthAfrica/direct-delivery/pull/253 should cut down the bulk of conflicts. The date strategy should cover the rest of the cases.

**Comment by tlvince** [comment]
Closing in favour of https://github.com/eHealthAfrica/direct-delivery/issues/255.
