### ISSUE TITLE
planning: when updates are made to the schedule, the remainder of the uploaded facilities get overwritten with blanks

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery-dashboard#334]
i.e., when the driver information is added, for the first facility after the schedule has been uploaded, the remainder of the schedule goes blank

**Comment by freefony** [comment]
i witnessed a different behavior with this, the driver changed for certain deliveries, not all row, and this is because our current data model ties deliveries to drivers for each day:
driver
     -delivery1
          -- date
          --health facility name
     -delivery2
          --date
         --health facility name

so if you change the driver, for delivery1, it will automagically change driver for delivery2.
  While this is logical, if we are to stick to it, i think we need to make it possible for a delivery to be moved from one driver to another.

**Comment by janetbutts** [comment]
@yusufscratch, please revisit and test after the split document task on direct-delivery is resolved

**Comment by yusufumars** [comment]
Tested the split document (Uploadschedule info>edit driver id) and its a Pass. Deliveries 1, 2, 3...are able to have different driver id without erasing or automatically changing other schedules.

_NOTE_ However when editing delivery schedule, if Delivery date is not set, it defaults at 1970-01-01

**Comment by freefony** [comment]
I think i pushed a PR to fix the date thing.
